/**
 * Full page examples routes
 */
export { default as applicantDetails } from './applicant-details/index.mjs'
export { default as cookieBannerEssentialCookies } from './cookie-banner-essential-cookies/index.mjs'
export { default as cookieBannerServerSide } from './cookie-banner-server-side/index.mjs'
export { default as haveYouChangedYourName } from './have-you-changed-your-name/index.mjs'
export { default as feedback } from './feedback/index.mjs'
export { default as howDoYouWantToSignIn } from './how-do-you-want-to-sign-in/index.mjs'
export { default as makeAPayment } from './make-a-payment/index.mjs'
export { default as search } from './search/index.mjs'
export { default as searchThree } from './search-three-pages/index.mjs'
export { default as passportDetails } from './passport-details/index.mjs'
export { default as updateYourAccountDetails } from './update-your-account-details/index.mjs'
export { default as uploadYourPhoto } from './upload-your-photo/index.mjs'
export { default as uploadYourPhotoSuccess } from './upload-your-photo-success/index.mjs'
export { default as whatIsYourAddress } from './what-is-your-address/index.mjs'
export { default as whatAreYourBankDetails } from './what-are-your-bank-details/index.mjs'
export { default as whatIsYourDateOfBirth } from './what-is-your-date-of-birth/index.mjs'
export { default as whatIsYourNationalInsuranceNumber } from './what-is-your-national-insurance-number/index.mjs'
export { default as whatIsYourNationality } from './what-is-your-nationality/index.mjs'
export { default as whatIsYourTelephoneNumber } from './what-is-your-phone-number/index.mjs'
export { default as whatIsYourPostcode } from './what-is-your-postcode/index.mjs'
export { default as whatWasTheLastCountryYouVisited } from './what-was-the-last-country-you-visited/index.mjs'
export { default as willYouBeTravellingTo } from './will-you-be-travelling-to-any-of-these-countries/index.mjs'
