name: Diff changes to npm package

on:
  workflow_call:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  generate-diff:
    name: Generate diff
    runs-on: ubuntu-latest

    # Skip workflows other than PRs such as merges to `main` but
    # also when token write permissions are unavailable on forks
    if: ${{ github.event.pull_request && !github.event.pull_request.head.repo.fork }}

    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0 # Need to also checkout the base branch to compare

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Set up diff drivers
        run: |
          npm install -g js-beautify
          git config diff.minjs.textconv "js-beautify --editorconfig --type js"
          git config diff.mincss.textconv "js-beautify --editorconfig --type css"

      - name: Generate diff
        run: |
          npm i -w @govuk-frontend/template-divergence
          npm start -w @govuk-frontend/template-divergence

      - name: Add comment to PR
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { commentDiffs } = await import('${{ github.workspace }}/.github/workflows/scripts/comments.mjs')
            const { getTemplateDiffs } = await import('${{ github.workspace }}/workbench/template-divergence/index.mjs')

            // PR information
            const issueNumber = ${{ github.event.pull_request.number }}
            const commit = '${{ github.event.pull_request.head.sha }}'

            const diffFileNames = await getTemplateDiffs();

            const diffs = diffFileNames.map(diffFileName => ({
              path: `${{ github.workspace }}/workbench/template-divergence/dist/${diffFileName}`,
              titleText: `Template diff: ${diffFileName}`,
              markerText: `template/${diffFileName}`,
              skipEmpty: true
            }))

            console.log(diffs);

            await commentDiffs({ github, context, commit }, issueNumber, diffs)
