name: 'RELEASE: Publish release (GitHub and npm)'
run-name: 'RELEASE: Publish release (GitHub and npm) to ${{inputs.environment}}'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - test
          - production

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment == 'production' && 'production' || null }}
    permissions:
      id-token: write
    uses: ./.github/workflows/publish-to-npm-standalone.yaml
    with:
      environment: ${{ inputs.environment }}
  publish-release-to-github:
    needs: [publish-to-npm]
    name: Publish release to GitHub
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment == 'production' && 'production' || null }}
    permissions:
      id-token: write
    uses: ./.github/workflows/publish-release-to-github.yaml
    with:
      environment: ${{ inputs.environment }}
