name: 'RELEASE: npm publish'

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-22.04
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      # For OIDC, we need npm 11.5.1 or later
      - name: Update npm
        run: npm install -g npm@11.6.0

      - name: Install dependencies
        run: npm ci

      - name: Generate tag
        id: generate_tag
        run: |
          TAG=$(npm run generate-npm-tag --silent)
          echo "NPM_TAG=${TAG}" >> $GITHUB_OUTPUT

      - name: Build npm package
        run: npm run build:package

      - name: Publish to npm
        run: npm publish --workspace govuk-frontend --provenance --tag ${{steps.generate_tag.outputs.NPM_TAG}}
